name: ci
on:
  push:
    branches:
      - main
  pull_request:
env:
  GO_VERSION: '1.20'
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.go.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: go
        uses: tj-actions/changed-files@v36
        with:
          files: |
            go
            .github/workflows/ci.yml
  go-lint:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.go == 'true'
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52
          working-directory: go
          args: --timeout=5m
  go-test:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.go == 'true'
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: go/go.sum
      - uses: actions/checkout@v3
      - name: Test
        working-directory: go
        run: go test -v ./...
